### ISSUE TITLE
Custom profile pictures?

### ISSUE THREAD

**Issue by artelephantb** [DigiWorm0/LevelImposter-Web#2]
This is just an idea, but are you able to add a change profile picture? (Also side note, your program is amazing!) 😀

**Comment by DigiWorm0** [comment]
Hi, thank you for the suggestion. This feature was done in [56c70fc](https://github.com/DigiWorm0/LevelImposter-Web/commit/56c70fc6ba8eae28b28e255b44e5ceac5463a436) but it has not yet been deployed publically. This feature will be available in the next couple of days.

**Comment by artelephantb** [comment]
Thanks very much!
